name: Website Uptime Monitor

on:
  schedule:
    - cron: '*/5 * * * *'  # 每30分钟检测一次
  workflow_dispatch:        # 允许手动触发

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v3

    - name: 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: 安装依赖
      run: pip install requests

    - name: 运行网站监控脚本
      env:
        MONITOR_URL: ${{ secrets.MONITOR_URL }}
        EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: python check_website.py
